### ISSUE TITLE
Exposing axios instance for test

### ISSUE THREAD

**Issue by tiarebalbi** [supercharge/sttp#1]
**Description:**
During tests is hard to mock the HTTP requests created by the `Sttp` library because the axios instance is set as private.  Would be possible to expose the `axios` instance in the `Sttp` class?

**Example:**

```js
import MockAdapter from 'axios-mock-adapter';

describe('My Test', () => {
    it('should be able to authenticate successfully', async () => {
      const mock = new MockAdapter(Sttp.axios);

      mock.onPost('https://api.auth.com/oauth/token').reply(200, {
        access_token: '123',
        refresh_token: 'v1.321',
        id_token: '1234',
        scope: 'openid profile email address phone offline_access',
        expires_in: 86400,
        token_type: 'Bearer',
      });

      const response = await Sttp.withBasicAuth('demo', 'demo')
        .withBaseUrl('https://api.auth.com')
        .post('/oauth/token', {....});

      expect(response).toMatchSnapshot();
    });
  });
```

**Reference:**
<img width="479" alt="Screenshot 2022-01-23 at 10 29 12" src="https://user-images.githubusercontent.com/103419/150674371-5e6a025a-2b70-48df-aee3-be39e9ee24cc.png">

**Comment by marcuspoehls** [comment]
@tiarebalbi Hey Tiarê, good idea to expose the Axios instance.

Do you want to submit a pull request that adds an `axios()` method returning the Axios instance?

**Comment by tiarebalbi** [comment]
Yep! I will prepare the changes.

**Comment by marcuspoehls** [comment]
Thank you!

**Comment by tiarebalbi** [comment]
PR created #2

**Comment by marcuspoehls** [comment]
@tiarebalbi I’ve published version `1.3.0` to NPM. It contains the new `axios()` method exposing the underlying Axios instance

**Comment by tiarebalbi** [comment]
Thank you very much, this will unblock me here!

**Comment by marcuspoehls** [comment]
Awesome! Thank you for your help!
