### ISSUE TITLE
To add statusText in SttpResponse

### ISSUE THREAD

**Issue by godwinpinto** [supercharge/sttp#3]
**Description**
While the library has option to get the SttpResponse status method, It would be good to have the statusText which is missing. This might help show the message for technical support perspective in addition to status, specially when users sent screenshot of problem. 

**Solution**
Exposing the statusText method.

Thank you for the great library.

**Comment by marcuspoehls** [comment]
@godwinpinto Hey Godwin, nice idea. Can you please submit a pull request adding the requested method? 🙂

**Comment by marcuspoehls** [comment]
@godwinpinto I’ve published `v1.4.0` including the new `response.statusText()` method. Thank you for contributing it!
